google:
  service: GCS
  project: image-repo-db
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: image_uploads_repo

google_dev:
  service: GCS
  project: image-repo-db
  credentials: <%= Rails.root.join("config/secrets/image-repo-db.json") %>
  bucket: image_uploads_repo
